---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Provision a set of instances
      amazon.aws.ec2_instance:
        region: "us-east-1"
        key_name: dlambright_s14
        count: 2
        security_group: launch-wizard-7
        instance_type: t2.micro
        network:
          assign_public_ip: true
        vpc_subnet_id: subnet-d37640ec
        image:
          id: "ami-025219984d88a5203"
        wait: true
        tags:
          Name: Demo

    - name: find all instances with tag Demo that are running or pending
      amazon.aws.ec2_instance_info:
        filters:
          "tag:Name": "Demo"
          instance-state-name: ["running", "pending"]
      register: ec2

    - name: add all found instances to hostgroup
      add_host:
        hostname: "{{ item.public_ip_address }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_ip_address }}"
        port: 22
        state: started
      with_items: "{{ ec2.instances }}"

- name: Configure instances
  hosts: launched
  tasks:
    - name: Download
      yum:
        name: screen
        state: latest
      become: yes
