- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    - name: run lambda function
      lambda:
        region: "us-east-1"
        state: present
        name: my_lambda
        zip_file: lambda.py.zip
        role: "basic_lambda_role"
        runtime: python3.7
        handler: lambda.my_lambda
        tags:
          'responsible party': uml@example.com

